### ISSUE TITLE
Problems with the camera and fleet synchronization

### ISSUE THREAD

**Issue by rafaelje** [flyve-mdm/flyve-mdm-glpi#31]
### Expected behavior
Put enable again the camera when change the fleet on website

### Actual behavior
Always keep the camera disabled nothing change if send a new fleet or modify it

### Environment Details
- Flyve MDM version: 0.99.46

### Steps to reproduce the behavior

1. Install the app and connect the device
2. Create a new fleet empty
3. Modify the fleet
4. Make a ping

**Comment by btry** [comment]
Hi, 

I need clarification about step 3: do you mean you change the fleet associated to your device ?

**Comment by SoUnd001** [comment]
@btry :/

**Comment by ajsb85** [comment]
@SoUnd001 We need to check with these steps:

0.- Enroll a device
1.- Create a fleet
2.- Disable camera policy = true
3.- Save fleet
4.- Add fleet to device
5.- Check the device
6.- Edit fleet
7.- Disable camera policy = false
8.- Save fleet
9.- Check the device

Do you agree @btry0 ?

**Comment by btry** [comment]
Yes.

**Comment by ajsb85** [comment]
The Web UI works to edit this policy

https://demo.flyve.org/glpi/apirest.php/PluginFlyvemdmFleet_Policy
## Request
PUT `{"input":{"id":39,"value":0}}`
## Response
`[{"39":true,"message":""}]`

**Comment by rafaelje** [comment]
I try with the steps 1 for 9 severals times:

1.- Create a fleet
2.- Disable camera policy = true
3.- Save fleet
4.- Add fleet to device
5.- Check the device
6.- Edit fleet
7.- Disable camera policy = false
8.- Save fleet
9.- Check the device

I try to leave my device to start from the beginning but lose connection and was impossible connect again because I can't read QR once your are connected

**Comment by SoUnd001** [comment]
FMMMMMMM i didn;t commented here wtf?

**Comment by ajsb85** [comment]
Already confirmed.

No way to enable camera.

- Disable policy
- Change fleet
- Delete fleet

![image](https://cloud.githubusercontent.com/assets/663460/25656046/8abe338c-2ff7-11e7-8dd7-0d838991bf4e.png)

![image](https://cloud.githubusercontent.com/assets/663460/25656049/8e6374c0-2ff7-11e7-8450-913023185d0c.png)

**Comment by ajsb85** [comment]
This issue is related to the Android app, then it's invalid here, I added the label "invalid" and I will close.
