### ISSUE TITLE
HTTP 500 when creating an invitation - GD extension missing

### ISSUE THREAD

**Issue by btry** [flyve-mdm/flyve-mdm-glpi#9]
### Expected behaviour

Invitation  created successfully

### Actual behaviour

HTTP 500
POST glpi/apirest.php/PluginStorkmdmInvitation

### Environment Details

GLPi contains data from asset management and helpdesk

** Php extension GD was missing **

### Steps to reproduce the behaviour

1. Try to invite a user

### Screenshots, backtraces or logs

Please check your logs for passwords, device serial numbers, IP addresses or any sensitive content

php-errors.log
```
not available yet
```

sql-errors.log
```
not available yet
```

HTTP server error log
```
not available yet
```

**Comment by blanchouins** [comment]
HTTP Server log 
```
[23/Dec/2016:14:34:08 +0100] "GET /glpi/apirest.php/User HTTP/1.1" 200 103252 "http://ocsinventory-ng:9001/" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0"
[23/Dec/2016:14:34:08 +0100] "GET /glpi/apirest.php/Computer?expand_dropdowns=true HTTP/1.1" 200 203349 "http://ocsinventory-ng:9001/" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0"
[23/Dec/2016:14:34:19 +0100] "OPTIONS /glpi/apirest.php/PluginStorkmdmInvitation HTTP/1.1" 200 600 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0"
[23/Dec/2016:14:34:19 +0100] "POST /glpi/apirest.php/PluginStorkmdmInvitation HTTP/1.1" 500 354 "http://ocsinventory-ng:9001/" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0"
```
No sql-errors.log file and no trace about problem in php-errors.log

**Comment by btry** [comment]
I think the log is from the file access.log. It only contains log of requests, without details if error. 

Can you check error.log in the same directory ? it should contain a backtrace.

**Comment by blanchouins** [comment]
You've right, here the content of error.log

[Fri Dec 23 15:43:06.507164 2016] [:error] [pid 21316] [client IP:62934] PHP Fatal error:  Call to undefined function imagecreatefromstring() in /var/www/html/glpi/plugins/storkmdm/inc/invitation.class.php on line 293, referer: http://ocsinventory-ng:9001/

**Comment by btry** [comment]
Ok

It appears you don't have the GD extension for PHP in your system. In GLPi go to **Cofiguration > General > tab System**

Read the **Server** section and check gd is in the available extensions. If not, install it.

I'll add a check for this extension in development version.

Thank you for your valuable feedback.

**Comment by blanchouins** [comment]
It's OK now, I can send invitation by mail.

Invitation don't include the download link of android application. 

I downloaded application from Google Play, but I can't enroll my device. When app stated, asked me to enter my name, email, and to create certificate. All steps are OK, but when clicking to "Start Enrollment", application return me "fail" message

**Comment by btry** [comment]
Ok, this is an other problem. I leave this ticket open for reminder about GD check.

For the enrollment process, let's open a new one.

**Comment by btry** [comment]
fixed
